apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ray-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://ray-project.github.io/kuberay-helm/
      chart: ray-cluster
      targetRevision: "1.3.0"
      helm:
        valueFiles:
          - $values/apps/ray-cluster/values.yaml
    - repoURL: https://github.com/samuelio-labs/ml-platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ray-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
