apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart — Bitnami MinIO (Broadcom repo)
    - repoURL: https://repo.broadcom.com/bitnami-files
      chart: minio
      targetRevision: "17.0.21"
      helm:
        valueFiles:
          - $values/manifests/minio/values.yaml
    # Values source — our infra repo
    - repoURL: https://github.com/samuelio-labs/ml-platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
