apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart — Bitnami PostgreSQL
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "18.5.11"
      helm:
        valueFiles:
          - $values/manifests/postgresql/values.yaml
    # Values source — our infra repo
    - repoURL: https://github.com/samuelio-labs/ml-platform-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
